### ISSUE TITLE
Found "Cthulhu Mythos", should probably be "Cthulhumyten"

### ISSUE THREAD

**Issue by FinitelyFailed** [Rangertheman/coc7-babele-sv#2]
Minor error, but I think that this line:
"CoC7.YouGainedCthulhuMythos":"Ditt sinne bävar inför den utomvärldsliga uppenbarelsen (+{value}% Cthulhu Mythos)",

Should be:
"CoC7.YouGainedCthulhuMythos":"Ditt sinne bävar inför den utomvärldsliga uppenbarelsen (+{value}% Cthulhumyten)",

**Comment by Rangertheman** [comment]
Stort tack/Thank you very much! Will change this in the next version.
